-- ============================================================
-- V11: 把「这批推荐是怎么算出来的」存下来
-- ============================================================
-- 前置：V9（recommendations）、V7（places）
--
-- 做的是哪件事：让 AI 生成推荐理由时，能**查到**当初这一批推荐是在
-- 什么处境下、按什么因子算出来的。
--
-- 【为什么非存不可】
--
-- 推荐和理由是两次请求（推荐要秒回，AI 要几秒，不能绑在一起）。
-- 第二次请求只能从数据库重建当时的判断，而这些数据原本**算完就丢了**：
-- 五个因子只在 RecommendationService 的内存里存在过一瞬间，
-- 数据库里只留了个乘完的总分 score。
--
-- 结果就是 AI 只能对着一个 "63%" 干瞪眼。而 63% 本身说明不了任何事——
-- 同样是 63%，可能是"兴趣很合但有点远"，也可能是"兴趣一般但就在楼下"，
-- 对用户的意义完全相反。**没有拆解，AI 只能编**，而这正是当初先把
-- 打分拆解做出来、再做理由的顺序原因。
--
-- ⚠️ 只新增这一个迁移文件，**绝不要回头改 V1~V10**。
--    改已执行过的脚本会让所有跑过的库校验和失败、直接起不来。
-- ============================================================

-- ------------------------------------------------------------
-- 1. recommendations 加五个因子列
-- ------------------------------------------------------------
-- 【⚠️ 为什么允许 NULL】
--
-- 和 V3 给 ai_reports 加 provider 是一样的道理：**留 NULL 表示"未知"，
-- 语义准确**。
--
-- 这个功能上线之前产生的推荐记录，它们的因子当时根本没有被计算保存过
-- （不是"算出来是 0"）。硬填一个默认值等于编造历史——
-- 填 1 会显得"五个因子都没影响"，填 0 更糟，乘起来是 0 但 score 明明不是 0，
-- 两份数据自相矛盾。
--
-- NULL 的读法很明确：「这条推荐早于 V11，没有可追溯的因子」。
--
-- 范围 0.000 ~ 1.000：引擎保证五个因子相乘等于 score，而 score 有
-- CHECK (score BETWEEN 0 AND 1) 卡着，所以每个因子也必然在这个区间内。
ALTER TABLE recommendations
    ADD COLUMN interest_factor NUMERIC(4,3),
    ADD COLUMN distance_factor NUMERIC(4,3),
    ADD COLUMN quality_factor  NUMERIC(4,3),
    ADD COLUMN state_factor    NUMERIC(4,3),
    ADD COLUMN weather_factor  NUMERIC(4,3);

COMMENT ON COLUMN recommendations.interest_factor IS
    '兴趣匹配度 0~1，主信号。NULL 表示该推荐早于 V11，因子未记录。';

-- 五因子都必须落在 0~1，且**乘起来必须等于 score**。
-- 后者没法用 CHECK 表达（跨行/浮点），靠 RecommendationEngineTest 里
-- "五因子相乘精确等于 score" 那条不变量测试守着。
ALTER TABLE recommendations
    ADD CONSTRAINT ck_recommendations_factors
        CHECK (
            (interest_factor IS NULL OR interest_factor BETWEEN 0 AND 1) AND
            (distance_factor IS NULL OR distance_factor BETWEEN 0 AND 1) AND
            (quality_factor  IS NULL OR quality_factor  BETWEEN 0 AND 1) AND
            (state_factor    IS NULL OR state_factor    BETWEEN 0 AND 1) AND
            (weather_factor  IS NULL OR weather_factor  BETWEEN 0 AND 1)
        );

-- ------------------------------------------------------------
-- 2. 新建「推荐批次」表：这批推荐当时的处境
-- ------------------------------------------------------------
-- 【为什么要单独一张表，而不是塞进 recommendations 的每一行】
--
-- 处境是**批次级**的事实，不是地点级的。同一批的三个地点共享同一份处境
-- （同样几点、同样还剩 240 分钟、同样下着雨），塞进 recommendations
-- 就是把同一份数据抄三遍——抄三遍就会有"三行对不上"的可能，
-- 而那种数据错误事后根本查不出来哪个是对的。
--
-- 表和行的关系由此变得清楚：
--     recommendation_batches  1 ──< 3  recommendations
--     （这批是怎么算的）              （算出来是哪几个地方）
--
-- 【顺带补上的一个真实缺口】
--
-- 在这之前，处境算完就整个丢掉了——"用户是在什么情况下接受了这条推荐"
-- 这个信息从来没有落过盘。存下来之后，计划书第十九节关心的
-- "推荐接受率"才有可能做真正的归因分析（比如"下雨天用户更接受哪类地方"）。
CREATE TABLE recommendation_batches (
    id       BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    batch_no INTEGER NOT NULL,

    -- ---- 用户坐标对应的人话地名，可能没有（没配高德 / 上游失败）----
    location_label VARCHAR(128),

    -- ---- "此刻的处境"：这一批是按什么算的 ----
    context_time      TIME    NOT NULL,   -- 算的时候是几点
    remaining_minutes INTEGER NOT NULL,   -- 还剩多少可玩时间
    max_distance_km   NUMERIC(5,2) NOT NULL,
    max_ticket_price  INTEGER,            -- NULL = 不限

    -- 状态存**枚举名**（TIRED）而不是中文（"有点累了"）。
    -- 中文展示名是 TravelState 枚举上的产品文案，会改；
    -- 存进数据库就会和代码里的定义脱节，改了枚举文案老数据还是旧的。
    -- 重建提示词时用 TravelState.valueOf(...).label() 现取中文。
    --
    -- 用逗号分隔的字符串而不是 TEXT[]：取值最多三个、只读不查，
    -- 而数组类型在 JPA 侧要额外配置才能映射。够用就好。
    states          VARCHAR(128) NOT NULL DEFAULT '',
    -- ⚠️ 单独记住"哪些是系统自己推断的"。AI 写理由时不能把
    -- 系统猜的"你饿了"说成用户说的——那是把猜测当成事实转述出去。
    inferred_states VARCHAR(128) NOT NULL DEFAULT '',

    -- ---- 天气，可能没有（没配高德 / 上游失败 / 境外）----
    weather_condition   VARCHAR(64),
    weather_temperature NUMERIC(4,1),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_recommendation_batches_session
        FOREIGN KEY (session_id) REFERENCES test_sessions (id) ON DELETE CASCADE,
    -- 一个会话的某一批只能有一行处境
    CONSTRAINT uq_recommendation_batches UNIQUE (session_id, batch_no),
    CONSTRAINT ck_recommendation_batches_batch CHECK (batch_no >= 1),
    CONSTRAINT ck_recommendation_batches_remaining CHECK (remaining_minutes > 0)
);

COMMENT ON TABLE recommendation_batches IS
    '每一批推荐当时用掉的处境。用来在生成 AI 理由时重建"当初是怎么算的"。';

-- 查"某个会话最新一批"是生成理由时最常见的读法
CREATE INDEX idx_recommendation_batches_session
    ON recommendation_batches (session_id, batch_no DESC);
