-- ============================================================
-- V1: 初始化表结构
-- ============================================================
-- 对应计划书第六节的 6 张表。
-- 设计要点（详见 docs/CODE_GUIDE.md）：
--   1. 主键统一用 GENERATED BY DEFAULT AS IDENTITY，配合 JPA 的 GenerationType.IDENTITY
--   2. 时间统一用 timestamptz（带时区），配合 Java 的 Instant
--   3. 分数用 numeric(5,2)，保留 2 位小数且无浮点误差
--   4. 表结构由 Flyway 管理，Hibernate 只做校验（ddl-auto=validate）
-- ============================================================

-- ------------------------------------------------------------
-- users: V0.1 不做登录，这张表先建好，user_id 允许为空
-- ------------------------------------------------------------
CREATE TABLE users (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_username UNIQUE (username)
);

-- ------------------------------------------------------------
-- questions: 题库
--   dimension      取值见 Java 枚举 Dimension
--   reverse_scored 为 true 时，计分需要做 6 - score 的镜像反转
--   sort_order     决定前端展示顺序（维度已交错排列，避免作答定势）
-- ------------------------------------------------------------
CREATE TABLE questions (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content        VARCHAR(500) NOT NULL,
    dimension      VARCHAR(32)  NOT NULL,
    reverse_scored BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order     INT          NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_questions_sort_order UNIQUE (sort_order),
    CONSTRAINT ck_questions_dimension CHECK (dimension IN (
        'OPENNESS', 'EXTRAVERSION', 'CONSCIENTIOUSNESS',
        'AGREEABLENESS', 'EMOTIONAL_STABILITY'
    ))
);

-- ------------------------------------------------------------
-- test_sessions: 一次测试会话
--   status 用于保证 submit 的幂等性（已提交的会话不能重复提交）
--   user_id 现在允许为空，V0.2 接入登录后再约束
-- ------------------------------------------------------------
CREATE TABLE test_sessions (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    submitted_at TIMESTAMPTZ,
    CONSTRAINT ck_test_sessions_status CHECK (status IN ('IN_PROGRESS', 'SUBMITTED'))
);

-- ------------------------------------------------------------
-- answers: 会话中的每一道作答
--   uq_answers_session_question 让"重复提交同一题"变成一次 UPDATE 而不是插入脏数据
-- ------------------------------------------------------------
CREATE TABLE answers (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT      NOT NULL REFERENCES test_sessions (id) ON DELETE CASCADE,
    question_id BIGINT      NOT NULL REFERENCES questions (id),
    score       INT         NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_answers_session_question UNIQUE (session_id, question_id),
    CONSTRAINT ck_answers_score CHECK (score BETWEEN 1 AND 5)
);

-- ------------------------------------------------------------
-- personality_profiles: 计算出的 5 维画像
--   session_id 上的唯一约束 + 会话的 status 字段，构成双层幂等防守：
--     应用层发现已存在就返回 409，数据库层作为最后的兜底
--   分数已归一化到 0.00 ~ 100.00
-- ------------------------------------------------------------
CREATE TABLE personality_profiles (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id          BIGINT       NOT NULL,
    openness            NUMERIC(5,2) NOT NULL,
    extraversion        NUMERIC(5,2) NOT NULL,
    conscientiousness   NUMERIC(5,2) NOT NULL,
    agreeableness       NUMERIC(5,2) NOT NULL,
    emotional_stability NUMERIC(5,2) NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_personality_profiles_session UNIQUE (session_id),
    CONSTRAINT fk_personality_profiles_session
        FOREIGN KEY (session_id) REFERENCES test_sessions (id) ON DELETE CASCADE,
    CONSTRAINT ck_profiles_range CHECK (
        openness            BETWEEN 0 AND 100 AND
        extraversion        BETWEEN 0 AND 100 AND
        conscientiousness   BETWEEN 0 AND 100 AND
        agreeableness       BETWEEN 0 AND 100 AND
        emotional_stability BETWEEN 0 AND 100
    )
);

-- ------------------------------------------------------------
-- ai_reports: AI 生成的个性化反馈
--   V0.1 只建表，不实现写入逻辑（/ai-report 端点返回 501）
-- ------------------------------------------------------------
CREATE TABLE ai_reports (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT      NOT NULL REFERENCES personality_profiles (id) ON DELETE CASCADE,
    content    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------
-- 索引：按实际查询路径建，不盲目加
-- ------------------------------------------------------------
CREATE INDEX idx_questions_dimension ON questions (dimension);
CREATE INDEX idx_answers_session     ON answers (session_id);
CREATE INDEX idx_ai_reports_profile  ON ai_reports (profile_id);
