-- ============================================================
-- V9: 旅行画像 + 推荐记录 + 用户反馈
-- ============================================================
-- 补齐 TravelMind 的数据链路：
--     答题 → 旅行画像 → 推荐 Top 3 → 用户反馈
--
-- 前置：V7（places，推荐要外键引用它）、V8（test_sessions.scale）
-- ============================================================

-- ------------------------------------------------------------
-- 1. 旅行画像
-- ------------------------------------------------------------
-- 和 personality_profiles 是**平行的两张表**，不是一张通用表。
--
-- 为什么不做成通用的 (session_id, dimension, score) 行式结构？
-- 因为那样每次读画像都要做一次"行转列"，而且失去列级的类型约束。
-- 两个画像的维度集合是固定的、数量也少（5 和 8），
-- 用固定列换来查询简单、约束明确，是划算的。
--
-- 分数范围 0~100，含义和人格画像一致（V6 的归一化公式相同）。
--
-- 【为什么是 NUMERIC(5,2) 而不是 INTEGER】
--
-- 计分器 ScoringService.normalize() 返回的就是两位小数，personality_profiles
-- 也是 NUMERIC(5,2)。旅行量表**今天**恰好只出整数，因为每个维度只有 1 道题，
-- 分数只能落在 0/25/50/75/100——但那是"当前题目数量"的巧合，不是这个表的性质。
--
-- ScoringService 的设计卖点就是 itemCount 参数化（"扩题量不用改代码"）：
-- 哪天某个维度加到 2 道题，分数就变成 12.5 / 37.5 这种。
-- 用 INTEGER 存的话：Java 侧 int 装不下 12.5，要么编译不过、要么有人写个
-- Math.round 把它抹平成 13——而 CHECK 是 BETWEEN 0 AND 100，抹平后照样通过，
-- 不报任何错。这种"静默丢精度"是最难查的一类问题。
--
-- 两张画像表用同一个类型，读代码的人也不用再记"哪张是整数哪张是小数"。
CREATE TABLE travel_profiles (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      BIGINT        NOT NULL,
    nature          NUMERIC(5,2)  NOT NULL,
    culture         NUMERIC(5,2)  NOT NULL,
    food            NUMERIC(5,2)  NOT NULL,
    photography     NUMERIC(5,2)  NOT NULL,
    hidden_gems     NUMERIC(5,2)  NOT NULL,
    crowd_tolerance NUMERIC(5,2)  NOT NULL,
    walking         NUMERIC(5,2)  NOT NULL,
    planning        NUMERIC(5,2)  NOT NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT uq_travel_profiles_session UNIQUE (session_id),
    CONSTRAINT fk_travel_profiles_session
        FOREIGN KEY (session_id) REFERENCES test_sessions (id) ON DELETE CASCADE,
    CONSTRAINT ck_travel_profiles_range CHECK (
        nature BETWEEN 0 AND 100 AND culture BETWEEN 0 AND 100 AND
        food BETWEEN 0 AND 100 AND photography BETWEEN 0 AND 100 AND
        hidden_gems BETWEEN 0 AND 100 AND crowd_tolerance BETWEEN 0 AND 100 AND
        walking BETWEEN 0 AND 100 AND planning BETWEEN 0 AND 100
    )
);

-- ------------------------------------------------------------
-- 2. 推荐记录（只追加，不删除）
-- ------------------------------------------------------------
-- 每次请求推荐存一批（Top 3 = 3 行，同一个 batch_no）。存下来的理由：
--   1. 用户反馈要挂到某一条推荐上，没有记录就没法挂
--   2. "随使用次数增加，推荐接受率是否提升"（计划书第十九节的核心指标）
--      需要历史数据才算得出来
--
-- 【为什么要 batch_no，而不是"重新推荐就把旧的删掉"】
--
-- 天真的做法是每次重新生成前先 DELETE 掉这个会话的旧推荐。
-- 但 recommendation_feedback 挂在 recommendations 上，
-- 删推荐会**级联把用户点过的 👍/👎 一起删掉**——
-- 而反馈恰恰是这个项目里最该攒下来的数据（见下面第 3 节的说明）。
-- 每重新推荐一次就清空一次，攒了等于没攒。
--
-- 所以推荐记录是 append-only 的：重新推荐 = 新的一批（batch_no + 1），
-- 旧的那批连同它的反馈永远留着。这样"接受率是否随使用提升"才有历史可比。
--
-- ⚠️ 因此**不要在代码里写"按 sessionId 删除推荐"**。
-- 真要删，只应该发生在整个会话被删除的时候（下面的 ON DELETE CASCADE）。
--
-- 列名用 rank_no 而不是 rank：rank 是 SQL 的窗口函数关键字，
-- 虽然 PostgreSQL 允许它当列名，但写查询时容易需要加引号，
-- 换个名字省心。
CREATE TABLE recommendations (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT       NOT NULL,
    -- 这个会话的第几批推荐，从 1 开始
    batch_no    INTEGER      NOT NULL DEFAULT 1,
    rank_no     INTEGER      NOT NULL,
    place_id    BIGINT       NOT NULL,
    -- 0.000 ~ 1.000。用 numeric 不用 double：分数要展示、
    -- 要比较、要写进测试断言，浮点误差会带来持续的困扰。
    --
    -- ⚠️ 上界 1.000 是**引擎算出来的**，不是这里一厢情愿写死的：
    -- score = interest × 距离系数 × 质量系数，三个因子都 ≤ 1。
    -- 改引擎的打分公式时，必须保证最后的乘积仍然 ≤ 1，否则存库直接违反约束。
    score       NUMERIC(4,3) NOT NULL,
    -- AI 生成的推荐理由。V0 允许为空（AI 没配置时用规则文案兜底）。
    reason      TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_recommendations_session
        FOREIGN KEY (session_id) REFERENCES test_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_recommendations_place
        FOREIGN KEY (place_id) REFERENCES places (id),
    -- 同一批里同一个名次只能有一个地点
    CONSTRAINT uq_recommendations_rank UNIQUE (session_id, batch_no, rank_no),
    -- 名次从 1 开始。不给上界：返回 Top 3 还是 Top 20 是产品决定，
    -- 不该由一条 CHECK 约束替产品把路堵死。
    CONSTRAINT ck_recommendations_rank CHECK (rank_no >= 1),
    CONSTRAINT ck_recommendations_batch CHECK (batch_no >= 1),
    CONSTRAINT ck_recommendations_score CHECK (score BETWEEN 0 AND 1)
);

-- 查"某个会话最新一批推荐"是最常见的读法，所以索引带上 batch_no
CREATE INDEX idx_recommendations_session ON recommendations (session_id, batch_no);

-- ------------------------------------------------------------
-- 3. 用户反馈
-- ------------------------------------------------------------
-- 这是整个闭环里**最有价值的数据**。
--
-- 计划书第七节的产品原则第一条：
--     「测试只是初始猜测，真实行为和反馈更重要。」
--
-- 问卷只有 8 道题，粒度很粗（每维度 5 个取值）。真正让画像变准的
-- 是这里的反馈——用户点了"不喜欢"，那就是一个比问卷更可信的信号。
--
-- V0 只存下来，不改画像。等攒够数据再让反馈去反哺偏好
-- （那属于计划书里的 Phase 6「个性化」）。
CREATE TABLE recommendation_feedback (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT      NOT NULL,
    reaction          VARCHAR(16) NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- ⚠️ 这个 CASCADE 只应该由"整个会话被删除"触发（test_sessions 那层的级联），
    -- 不能由"重新生成推荐"触发——那等于把用户攒下来的反馈清了零。
    -- 推荐记录是 append-only 的（见上面第 2 节），所以正常情况下这里永远不会被触发。
    CONSTRAINT fk_feedback_recommendation
        FOREIGN KEY (recommendation_id) REFERENCES recommendations (id) ON DELETE CASCADE,
    -- 一条推荐只记一次反馈。用户改主意的话是 UPDATE 而不是插入第二条，
    -- 否则"接受率"这类统计会被重复数据污染。
    CONSTRAINT uq_feedback_recommendation UNIQUE (recommendation_id),
    CONSTRAINT ck_feedback_reaction CHECK (reaction IN ('LIKE', 'DISLIKE'))
);

COMMENT ON TABLE recommendation_feedback IS
    '用户对推荐的反应。比问卷更可信的信号，V0 只采集，Phase 6 再用来反哺画像。';
